### ISSUE TITLE
Schedule Enhancements

### ISSUE THREAD

**Issue by hendricksond** [jocosocial/swiftarr#225]
If we are able to get access to an improved schedule data source, add the following:

- Performers for official events
- Facilitators/organizers/panel members/whatever for shadow events

**Comment by cohoe** [comment]
I wonder if they could just list them in the text blob we get of the description. It's duplicate data for them but trivial to implement.

**Comment by challfry** [comment]
This is now in, although for shadow events it works a bit differently than envisioned here. Shadow event organizers can self-edit a Performer profile for themselves and link it to the events they're running. One profile per user, and they can only create/edit their profile during pre-registration. This way THO doesn't need to collect a bunch of extra data from shadow event organizers, format it and give it to us, just so that we can populate the db.
