### ISSUE TITLE
Performer Profiles

### ISSUE THREAD

**Issue by hendricksond** [jocosocial/swiftarr#226]
Scrape performer data from the official site. Import it into twitarr. Create API endpoints and web views for accessing the data.

If we get access to an improved event feed (#225), ensure the schedule has links to the performer profiles.

Bonus feature: Allow content management/editing once on board (typo fixes, removing last-minute-cancellations, adding last-minute-additions, etc).

**Comment by hendricksond** [comment]
If the official site's HTML is too inconsistent or difficult to scrape, we could populate the data by hand.

**Comment by challfry** [comment]
A bit of background: performer photos and blurbs are available on jococruise.com each year, and that site is whitelisted so cruisers can see it while aboard. The value of us copying it into Twitarr is in our ability to link performer profiles with other content. It's not worthwhile doing this just to copy stuff cruisers already have access to.

Showing a list of all the events a performer is participating in on that performer's page would be useful, particularly since we may be able to make that list update to match schedule changes. Linking to performer pages from event and forum pages would also be useful.

**Comment by challfry** [comment]
This is now in, and we have access to an improved event feed, so we can bulk import links. Mods and above can edit performer profiles on boat. We can't (yet) bulk import Performers themselves; instead there's a web form for creating/editing official performers. 

This feature also lets shadow cruise organizers create and edit performer profiles and link them to their events. They can only do this during the pre-registration period (not on boat).
