### ISSUE TITLE
StoredSettingsValue cannot default to False

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#346]
Setting `.defaultValue: false` on a `@StoredSetttingsValue` in `Settings.swift` such as `enablePreregistration` has no effect. The value is true until it is stored in Redis, after which assuming you've unchecked the checkbox or otherwise modified the value then it will act appropriately.

**Comment by challfry** [comment]
On my machine:

Adding
 ```	configLog.notice("Immediately after init, Settings.preregistration value: \(Settings.shared.enablePreregistration)")``` 
to `configureBundle()` in configure.swift shows the value is false right after init. 

Adding
```		configLog.notice("Just before reading stored settings, Settings.preregistration value: \(Settings.shared.enablePreregistration)")```
to the top of `configureStoredSettings()` shows the value as false just before loading stored values from Redis.

Adding
```		sleep(1)
		configLog.notice("Just after reading stored settings, Settings.preregistration value: \(Settings.shared.enablePreregistration)")```
to the bottom of `configureStoredSettings()` shows the value as having whatever value was stored in Redis.

The sleep(1) is there because Settings updates values asynchronously on its own dispatch queue.

I'm not sure what's going on here; maybe it's Linux-related?

**Comment by cohoe** [comment]
I was on my mac. I haven't chased this down at all, but what I observed was the check box being checked in the site admin ui when I expected it to be not.

**Comment by cohoe** [comment]
Example: On a fresh installation (no pre-existing Redis or Pg) after migration and startup, adding a print line to any function (I threw it in `settingsHandler` in `AdminController`) shows `Settings.shared.enablePreregistration` to be `true` rather than its expected `.defaultValue` of `false`.

**Comment by challfry** [comment]
Pushed a fix. The problem was in Foundation+Extensions; initializing a Bool from a RESPValue needs to return nil if Redis doesn't have a value stored for a key.
