### ISSUE TITLE
Add a link parser to FormatPostTextTag

### ISSUE THREAD

**Issue by challfry** [jocosocial/swiftarr#6]
In CustomLeafTags.swift:

FormatPostTextTag handles formatting the text contents of twarrtrs, forum posts, seamail, and fez posts for HTML display. The fn already does a bunch of transformations, but link detection and (for site links) shortening would be nice. That is, transform:

`http://joco.hollandamerica.com/tweets`

to:

`<a href="http://joco.hollandamerica.com/tweets">/tweets</a>`

for display.

**Comment by challfry** [comment]
Basic link detection is now in. It'd be even cooler if this was upgraded so that:

```http://joco.hollandamerica.com/tweets/42```

became:

```<a href=http://joco.hollandamerica.com/tweets/42>[A Tweet Link]</a>```

or similar. This means we'd have to add route parsing to the links.

**Comment by cohoe** [comment]
Since the server has multiple hostnames (`joco.hollandamerica.com`, `twitarr.com`) and none of them correspond with the Docker  runtime hostname (`0.0.0.0`) this effectively does not work. We pass in the server hostname to the tags here: 

https://github.com/challfry/swiftarr/blob/5b5b577b634a48baf1219cc58b3b0e4c9ddedf56/Sources/App/configure.swift#L324-L327

Which gets regex'd here:

https://github.com/challfry/swiftarr/blob/5b5b577b634a48baf1219cc58b3b0e4c9ddedf56/Sources/App/Site/CustomLeafTags.swift#L192-L197

And attempts to match here:

https://github.com/challfry/swiftarr/blob/5b5b577b634a48baf1219cc58b3b0e4c9ddedf56/Sources/App/Site/CustomLeafTags.swift#L155-L174

We should consider linking everything (regardless of hostname). This would also enable linking to function on custom hostnames that we don't know (like `twitarr.herokuapp.com`, `twitarr.apps.grantcohoe.com`, etc).

As it currently stands I can specify a link of `http://0.0.0.0/forum/DF3353C1-6642-4E1C-A10F-913F0C44C96B` which translates to text `/forum/DF3353C1-6642-4E1C-A10F-913F0C44C96B`. Stripping the hostname out feels a little funky but it is at least functional.

**Comment by cohoe** [comment]
It would be wonderful if we could use [NSDataDetector](https://developer.apple.com/documentation/foundation/nsdatadetector) but per https://github.com/apple/swift-corelibs-foundation/issues/4305 it has not been implemented in Foundation yet. Confirmed in that VSCode can't find the class. Big sad.
