### ISSUE TITLE
Deprecate the need for schedule munging

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#69]
It would be nice if we could deprecate the need to munge the incoming schedule from Sched. Currently the munger is manually configured with the date/time/delta of the change (we only had one) and write out a new file that we then import. I think we can achieve the same effect by presenting the schedule in PortTime vs DisplayTime since that's what Sched keys off of. Needs testing.

**Comment by challfry** [comment]
IIRC all the events in the .ics file from Sched.com are in EST/EDT, because (I think) Sched doesn't have a way to make individual events in a conference have different timezones, although it does handle DST. So, THO builds the schedule and then declares all the times should be interpreted as 'local time'. However, since the .ics file exports UTC times this makes the UTC times wrong. 

That is: an event is scheduled for noon on a day when we're in port at San Juan. San Juan is in AST (GMT-4). The event on Sched.com is set to start at 'noon', but that's interpreted by Sched as noon EST, which is 1 PM AST. The event in the ics file does not have any timezone information.

I believe the fix for this is going to be adding an admin feature where we can set all the timezone changes that will occur during the week. This will be in the form of: an array of "At this UTC time our timezone changes to UTC-4" values.

**Comment by challfry** [comment]
66c579eaff906e3c0e12faf1b830b49805be35d5 fixes this issue by adding a table of timezone changes. This table is loaded in from a seeds file, and we can update the file (with git) and re-load it into the db from the admin UI while the server's running.

With this change, Dates that are meant to indicate a 'local time' concept are stored in the db using the ship's Port timezone (where the ship embarks from), and adjusted to be the same 'local time' in the timezone the ship was/will be in at the Date when returned by API structures.

That is, for an Event that starts at Noon according to Sched.com, that value really means "Noon local time" but their .ics file will contain a Date object that equates to Noon EST. Remember that a Date is just a moment in time and has no timezone info. We store that Date value in the db. If the timezone table says the ship will be in the AST timezone at that Date, when returning the Date to clients the API layer converts the Date to noon AST, which equals 11:00 AM EST.
